M48
; DRILL file {KiCad 8.0.9} date 2025-05-16T14:56:25+0100
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-05-16T14:56:25+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.9
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
%
G90
G05
T1
X7.4565Y-3.4295
X7.4565Y-3.6571
T2
G00X4.9394Y-2.7579
M15
G01X4.9394Y-2.7815
M16
G05
M30
